# Generated by Django 6.0.4 on 2026-05-05 21:07

import core.models.user
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pin_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=core.models.user.profile_image_file_path)),
                ('is_admin', models.BooleanField(default=False)),
                ('should_change_password', models.BooleanField(default=True)),
                ('avatar_color', models.CharField(choices=[('primary', 'Primary'), ('pink', 'Pink'), ('red', 'Red'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('gray', 'Gray'), ('amber', 'Amber')], max_length=64)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('oauth_id', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_label', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(default='', max_length=64)),
                ('quota_size_in_bytes', models.BigIntegerField(blank=True, null=True)),
                ('quota_usage_in_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removing', 'Removing'), ('deleted', 'Deleted')], max_length=64)),
                ('profile_changed_at', models.DateTimeField(auto_now_add=True)),
                ('update_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at', 'id'], name='core_user_updated_9bc611_idx')],
            },
        ),
    ]
