# Generated by Django 6.0.4 on 2026-05-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['update_id'], name='core_user_update__61a1a6_idx'),
        ),
    ]
