# Generated by Django 6.0.4 on 2026-05-06 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_core_user_update__61a1a6_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.BinaryField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('device_type', models.CharField(default='', max_length=255)),
                ('device_os', models.CharField(default='', max_length=255)),
                ('app_version', models.CharField(blank=True, max_length=255, null=True)),
                ('update_id', models.UUIDField(default=uuid.uuid7)),
                ('is_pending_sync_reset', models.BooleanField(default=False)),
                ('pin_expires_at', models.DateTimeField(blank=True, null=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.session')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='core_sessio_token_c4948d_idx'), models.Index(fields=['update_id'], name='core_sessio_update__a2f406_idx')],
            },
        ),
    ]
