# Generated by Django 6.0.4 on 2026-05-12 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AuthUserV1', 'AuthUserV1'), ('UserV1', 'UserV1'), ('UserDeleteV1', 'UserDeleteV1'), ('AssetV1', 'AssetV1'), ('AssetV2', 'AssetV2'), ('AssetDeleteV1', 'AssetDeleteV1'), ('AssetExifV1', 'AssetExifV1'), ('AssetEditV1', 'AssetEditV1'), ('AssetEditDeleteV1', 'AssetEditDeleteV1'), ('AssetMetadataV1', 'AssetMetadataV1'), ('AssetMetadataDeleteV1', 'AssetMetadataDeleteV1'), ('PartnerV1', 'PartnerV1'), ('PartnerDeleteV1', 'PartnerDeleteV1'), ('PartnerAssetV1', 'PartnerAssetV1'), ('PartnerAssetV2', 'PartnerAssetV2'), ('PartnerAssetBackfillV1', 'PartnerAssetBackfillV1'), ('PartnerAssetBackfillV2', 'PartnerAssetBackfillV2'), ('PartnerAssetDeleteV1', 'PartnerAssetDeleteV1'), ('PartnerAssetExifV1', 'PartnerAssetExifV1'), ('PartnerAssetExifBackfillV1', 'PartnerAssetExifBackfillV1'), ('PartnerStackBackfillV1', 'PartnerStackBackfillV1'), ('PartnerStackDeleteV1', 'PartnerStackDeleteV1'), ('PartnerStackV1', 'PartnerStackV1'), ('AlbumV1', 'AlbumV1'), ('AlbumV2', 'AlbumV2'), ('AlbumDeleteV1', 'AlbumDeleteV1'), ('AlbumUserV1', 'AlbumUserV1'), ('AlbumUserBackfillV1', 'AlbumUserBackfillV1'), ('AlbumUserDeleteV1', 'AlbumUserDeleteV1'), ('AlbumAssetCreateV1', 'AlbumAssetCreateV1'), ('AlbumAssetCreateV2', 'AlbumAssetCreateV2'), ('AlbumAssetUpdateV1', 'AlbumAssetUpdateV1'), ('AlbumAssetUpdateV2', 'AlbumAssetUpdateV2'), ('AlbumAssetBackfillV1', 'AlbumAssetBackfillV1'), ('AlbumAssetBackfillV2', 'AlbumAssetBackfillV2'), ('AlbumAssetExifCreateV1', 'AlbumAssetExifCreateV1'), ('AlbumAssetExifUpdateV1', 'AlbumAssetExifUpdateV1'), ('AlbumAssetExifBackfillV1', 'AlbumAssetExifBackfillV1'), ('AlbumToAssetV1', 'AlbumToAssetV1'), ('AlbumToAssetDeleteV1', 'AlbumToAssetDeleteV1'), ('AlbumToAssetBackfillV1', 'AlbumToAssetBackfillV1'), ('MemoryV1', 'MemoryV1'), ('MemoryDeleteV1', 'MemoryDeleteV1'), ('MemoryToAssetV1', 'MemoryToAssetV1'), ('MemoryToAssetDeleteV1', 'MemoryToAssetDeleteV1'), ('StackV1', 'StackV1'), ('StackDeleteV1', 'StackDeleteV1'), ('PersonV1', 'PersonV1'), ('PersonDeleteV1', 'PersonDeleteV1'), ('AssetFaceV1', 'AssetFaceV1'), ('AssetFaceV2', 'AssetFaceV2'), ('AssetFaceDeleteV1', 'AssetFaceDeleteV1'), ('UserMetadataV1', 'UserMetadataV1'), ('UserMetadataDeleteV1', 'UserMetadataDeleteV1'), ('SyncAckV1', 'SyncAckV1'), ('SyncResetV1', 'SyncResetV1'), ('SyncCompleteV1', 'SyncCompleteV1')], max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ack', models.CharField(max_length=255)),
                ('update_id', models.UUIDField(default=uuid.uuid7)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
            options={
                'indexes': [models.Index(fields=['update_id'], name='core_syncch_update__9892db_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'type'), name='unique_session_per_type')],
            },
        ),
    ]
